# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yhi-TXLdAtTwglmFDS0BdK917Ljbe6cI
"""

from sklearn import datasets
from statistics import mean
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score

X, y = datasets.load_iris(return_X_y = True, as_frame = False)
nb = GaussianNB()

crossVal = cross_val_score(nb, X, y, cv = 5)
print(mean(crossVal))